// receiver
export const winIgnoreMouse = 'winIgnoreMouse'
export const winMouseMove = 'winMouseMove'
export const attemptChange = 'attemptChange'
export const usePreset = 'usePreset'
export const jumpLink = 'jumpLink'
export const copyText = 'copyText'
export const speakText = 'speakText'
export const setStore = 'setStore'
export const getStore = 'getStore'
export const removeChat = 'removeChat'
export const getChatList = 'getChatList'
export const addPrompt = 'addPrompt'
export const editPrompt = 'editPrompt'
export const removePrompt = 'removePrompt'
export const getPromptList = 'getPromptList'
export const setPluginPrompt = 'setPluginPrompt'
export const getPluginPrompt = 'getPluginPrompt'
export const changeLanguage = 'changeLanguage'

// sender
export const clipboard_change = 'clipboard_change'
export const selection_change = 'selection_change'
export const url_change = 'url_change'
export const setting_show = 'setting_show'
